[package]
name = "fs-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
rayon = "1.10.0"
thiserror = "2.0.3"

[[bin]]
name = "fs-rs"
path = "src/main.rs"
